---
route:
  group_by: ['instance', 'alert']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: slack
  routes:
    - receiver: slack
      continue: true
    - receiver: executor
receivers:
  - name: slack
    slack_configs:
      - api_url: https://hooks.slack.com/services/--masked--
        send_resolved: true
        channel: monitoring
        text: |-
          {{ range .Alerts }}<!here> {{ .Annotations.summary }}
          {{ .Annotations.description }}
          {{ end }}
  - name: executor
    webhook_configs:
      - url: http://localhost:8088