---
global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus_master
    scrape_interval: 5s
    static_config:
      - 'targets:': ['localhost:9090']
rule_files:
  - alert.yaml
alerting:
  alertmanagers:
    - scheme: http
      statics_configs:
        - targets:
            - 192.168.40.11:9093